/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("com.github.lookfirst:sardine:5.10")
    implementation("org.slf4j:slf4j-log4j12:1.7.33")
    implementation("org.apache.httpcomponents:httpclient:4.5.1")
    testImplementation("junit:junit:4.11")
}

group = "sk.uisav.icontrol"
version = "0.1"
description = "webdav"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
